// Pool contract ABI — only the functions we call from the frontend
export const POOL_ABI = [
  // ── Read ──────────────────────────────────────────────────────────────────
  {
    name: 'getAllReserves',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'string[]', name: '' }],
  },
  {
    name: 'getAllReserveData',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        type: 'tuple[]',
        name: '',
        components: [
          { name: 'totalDeposits', type: 'uint256' },
          { name: 'totalBorrows', type: 'uint256' },
          { name: 'supplyLiquidityIndex', type: 'uint256' },
          { name: 'borrowLiquidityIndex', type: 'uint256' },
          { name: 'lastUpdateTimestamp', type: 'uint256' },
          { name: 'liquidationThreshold', type: 'uint256' },
          { name: 'ltv', type: 'uint256' },
          { name: 'slope1', type: 'uint256' },
          { name: 'slope2', type: 'uint256' },
          { name: 'baseInterestRate', type: 'uint256' },
          { name: 'optimalUtilization', type: 'uint256' },
          { name: 'liquidationBonus', type: 'uint256' },
          { name: 'reserveFactor', type: 'uint256' },
          { name: 'borrowCap', type: 'uint256' },
          { name: 'supplyCap', type: 'uint256' },
          { name: 'priceFeed', type: 'address' },
          { name: 'tokenAddress', type: 'address' },
          { name: 'isActive', type: 'bool' },
          { name: 'isBorrowable', type: 'bool' },
          { name: 'reserveName', type: 'string' },
        ],
      },
    ],
  },
  {
    name: 'getReserveData',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'reserveName', type: 'string' }],
    outputs: [
      {
        type: 'tuple',
        name: '',
        components: [
          { name: 'totalDeposits', type: 'uint256' },
          { name: 'totalBorrows', type: 'uint256' },
          { name: 'supplyLiquidityIndex', type: 'uint256' },
          { name: 'borrowLiquidityIndex', type: 'uint256' },
          { name: 'lastUpdateTimestamp', type: 'uint256' },
          { name: 'liquidationThreshold', type: 'uint256' },
          { name: 'ltv', type: 'uint256' },
          { name: 'slope1', type: 'uint256' },
          { name: 'slope2', type: 'uint256' },
          { name: 'baseInterestRate', type: 'uint256' },
          { name: 'optimalUtilization', type: 'uint256' },
          { name: 'liquidationBonus', type: 'uint256' },
          { name: 'reserveFactor', type: 'uint256' },
          { name: 'borrowCap', type: 'uint256' },
          { name: 'supplyCap', type: 'uint256' },
          { name: 'priceFeed', type: 'address' },
          { name: 'tokenAddress', type: 'address' },
          { name: 'isActive', type: 'bool' },
          { name: 'isBorrowable', type: 'bool' },
          { name: 'reserveName', type: 'string' },
        ],
      },
    ],
  },
  {
    name: 'getUserPositions',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [
      {
        type: 'tuple[]',
        name: '',
        components: [
          { name: 'collateralAsset', type: 'string' },
          { name: 'collateralAssetPriceFeed', type: 'address' },
          { name: 'borrowAsset', type: 'string' },
          { name: 'borrowAssetPriceFeed', type: 'address' },
          { name: 'scaledDebt', type: 'uint256' },
          { name: 'collateralLocked', type: 'uint256' },
          { name: 'bufferPercent', type: 'uint256' },
        ],
      },
    ],
  },
  {
    name: 'checkPositionHealth',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'positionId', type: 'uint256' },
    ],
    outputs: [{ type: 'bool', name: '' }],
  },
  {
    name: 'getUserDepositBalance',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'reserveName', type: 'string' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ type: 'uint256', name: '' }],
  },
  // ── Write ─────────────────────────────────────────────────────────────────
  {
    name: 'deposit',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'reserveName', type: 'string' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'withdraw',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'reserveName', type: 'string' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'borrow',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'collateralName', type: 'string' },
      { name: 'borrowName', type: 'string' },
      { name: 'amount', type: 'uint256' },
      { name: 'bufferPercent', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'repay',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'collateralName', type: 'string' },
      { name: 'borrowName', type: 'string' },
      { name: 'positionId', type: 'uint256' },
      { name: 'repayAmount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'liquidate',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'positionId', type: 'uint256' },
    ],
    outputs: [],
  },
] as const

// ERC20 ABI — approve + balanceOf
export const ERC20_ABI = [
  {
    name: 'approve',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'allowance',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'decimals',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
] as const

// ─── Custom error selectors ────────────────────────────────────────────────
export const CUSTOM_ERRORS: Record<string, string> = {
  '0x095469b2': 'Reserve does not exist.',
  '0x05a80925': 'Reserve is not active.',
  '0x4a994a98': 'Supply cap exceeded for this reserve.',
  '0xe8b71a1e': 'Borrow cap exceeded for this reserve.',
  '0x3c9c72be': 'Max utilization exceeded — too much borrowed from this pool.',
  '0x9d1a0a0e': 'Asset is not borrowable.',
  '0x6d74e7df': 'Buffer too low — minimum is 5%.',
  '0x3de361ca': 'Buffer too high — maximum is 100%.',
  '0x7b44def6': 'Insufficient free collateral — deposit more collateral first.',
  '0x08a85454': 'Insufficient pool liquidity — not enough tokens in the pool.',
  '0x4e487b71': 'Insufficient user balance.',
  '0x5c7e4cfd': 'Wrong borrow asset for this position.',
  '0x4a2b35c7': 'Wrong collateral asset for this position.',
  '0xa8bcbbf0': 'No debt on this position.',
  '0x4e7f5a3c': 'No active position found.',
  '0xe91a8f87': 'Repay amount exceeds current debt.',
  '0x2b00b0a0': 'Position is healthy — cannot be liquidated.',
  '0x87d4498b': 'Invalid price from oracle.',
  '0x08c379a0': 'Transaction reverted.',
}
